[project]
name = "fact-checking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "imageio-ffmpeg>=0.6.0",
    "mistralai[realtime]>=2.9.4",
    "numpy>=2.0.0",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.52.4",
]
